# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ad2422c94ec4cefeddd486223dd6a09c18dc30242b2be336ff1c9a9a4034a063cd403d12cf935a74e5d391f9c3c647f510570ecd8424751de116fb213b5a50a

test:
  secret_key_base: 2523ad116df4276f44fc1b5cea6ee04f6c9214eb23b2b0ef7a9ebaba9a8bc84989a56280788251b16d82a2318a80b1543050392220d1299402b64f4641b334d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

# cp db/development.sqlite3 db/production.sqlite3
# RAILS_ENV=production rake assets:precompile
# export RAILS_SERVER_STATIC_FILES=true
# export SECRET_KEY_BASE=5ad2422c94ec4cefeddd486223dd6a09c18dc30242b2be336ff1c9a9a4034a063cd403d12cf935a74e5d391f9c3c647f510570ecd8424751de116fb213b5a50a
